### ISSUE TITLE
Incorrect durability values for some recipes

### ISSUE THREAD

**Issue by Dranni21312** [PunishXIV/Artisan#188]
Artisan 4.0.3.36 uses the incorrect durability value for some recipes, causing failed crafts. For instance, the cosmic exploration recipe for "Survey Sap" (id = 36178) at CRP lvl 55 has durability of 40, whereas Artisan reads it incorrectly as 35:

![Image](https://github.com/user-attachments/assets/f5425fdd-c1a2-44e4-aa61-8d6bdbda4195)

![Image](https://github.com/user-attachments/assets/6ca37e39-604c-4ed1-99fa-6c641104198e)

This causes the Raphael solver to fail.

**Comment by Kagekazu** [comment]
Mine shows 40 durability, but thats on standard recipe solver, not sure if it matters. 

![Image](https://github.com/user-attachments/assets/6cda2095-a1ad-49a8-aec5-9ea571bacfe9)

**Comment by Kagekazu** [comment]
Also do update to the latest version ^.^

**Comment by Dranni21312** [comment]
I think it might have something to do with crafter level scaling - I'm checking this on a level 55 carpenter. If I'm not mistaken, cosmic exploration recipes have different values based on job level and it looks like Artisan might not be applying these modifiers correctly.

> Also do update to the latest version ^.^

Will do

**Comment by Taurenkey** [comment]
When I did my initial findings of the level scaling, I had assumed that all things scaled according to the different level table. However it would seem durability doesn't, and it's only progress and quality that change. I must've gotten lucky with all the ones I checked for it to come out the same.

Fixed for next update.

**Comment by Taurenkey** [comment]
> This causes the Raphael solver to fail.

Just for the record, I have checked the raphael code and they didn't have this same bug as Artisan, so the macro it generates was for the correct durability. It should only fail in Artisan's simulator as a result.

**Comment by Dranni21312** [comment]
Thank you, I can see that this recipe is now solved correctly.

Before:

![Image](https://github.com/user-attachments/assets/023c400f-0719-4624-8528-b96868ee8142)

After:

![Image](https://github.com/user-attachments/assets/e0b73226-8cf0-4c63-ba59-6b7858ff3f57)

**Comment by Dranni21312** [comment]
After a few more tests, it looks like the fix isn't fully working for all recipes. For example, the recipe with ID = 36172 - Carpentry Supplies - is still failing due to incorrect durability:

![Image](https://github.com/user-attachments/assets/3d0946b5-c436-4076-83ed-8335da816ef3)

![Image](https://github.com/user-attachments/assets/f728017c-9b3b-4e59-8bb1-4cce67c555a5)

So it looks like the fix solved the problem for some recipes, but not all.

**Comment by Dranni21312** [comment]
Looking at the code, the current level table data is pulled in `Crafting.BuildCraftStateForRecipe()` using the following line:

`var lt = recipe.Number == 0 && stats.Level < 100 ? Svc.Data.GetExcelSheet<RecipeLevelTable>().First(x => x.ClassJobLevel == stats.Level) : recipe.RecipeLevelTable.Value;`

This doesn't seem to account for recipes with max adjustable job level. The following code can be a starting point to account for these:

```
var ltrId = recipe.MaxAdjustableJobLevel != 0
    ? Svc.Data.GetExcelSheet<GathererCrafterLvAdjustTable>().GetRow(recipe.MaxAdjustableJobLevel).RecipeLevel
    : recipe.RecipeLevelTable.RowId;

var lt = Svc.Data.GetExcelSheet<RecipeLevelTable>().GetRow(ltrId);
```

With this, durability appears to be calculated correctly, but there are some more issues, as the recipe is now treated as a level 100. More changes are likely required.
